name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  security-events: write
  actions: read
  checks: read
  pull-requests: read


env:
  PRERELEASE: "true"

# jobs
jobs:
  # setup provides all vars used in the process
  setup:
    name: "Set variables"
    runs-on: ubuntu-latest
    outputs:
      # TERRAFORM
      terraform_workspace: "default"
      terraform_version: ${{ steps.terraform_account_version.outputs.version }}
      # SEMVER & BRANCH NAMES
      branch_name: ${{ steps.semver.outputs.branch }}
      semver_tag: ${{ steps.semver.outputs.tag }}
    steps:
      # Check the code base
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
      # Find the terraform version details for account & env
      - name: "Parse terraform account version"
        id: terraform_account_version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@4f345be3f706950d1fdc05bc86383967a149bd99 # v4.3.4
        with:
          terraform_directory: ./terraform/account
      # semver tag
      - name: "Semver tag"
        id: "semver"
        uses: ministryofjustice/opg-github-actions/actions/semver@4f345be3f706950d1fdc05bc86383967a149bd99 # v4.3.4
        with:
          create_release: "false" # dont create the release at the moment
          prerelease: ${{ env.PRERELEASE }}
  # terraform linting
  terraform_lint:
    name: "Terraform linting"
    needs: [setup]
    uses: ministryofjustice/opg-github-workflows/.github/workflows/linting-infrastructure-terraform.yml@361d19a6d7b291dab5d46f04765239341a4ca86b # v3.16.0
    with:
      terraform_version: ${{ needs.setup.outputs.terraform_version }}
  # tfsec for terraform
  tfsec:
    needs: [setup, terraform_lint]
    name: "Run TFSec against the code base"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-to-github-security.yml@v3.16.0
  # codeql for python
  codeql_analysis:
    needs: [setup]
    name: "Run CodeQL against the code base"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-application-codeql-sast-to-github-security.yml@v3.16.0
    with:
      application_languages: '["python"]'

  # run all the tests
  tests:
    name: "Run Tests"
    needs:
      - setup
      - codeql_analysis
      - terraform_lint
      - tfsec
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      # RUN TEST SUITE
      - run: echo "RUN TEST SUITE HERE"

  # Docker build, trivy scan, ECR push as a matrix
  # The matrix loops over each app to build in a complicated
  # structure
  build_scan_push:
    name: "Docker build, trivy scan, ECR push"
    runs-on: ubuntu-latest
    # require all steps before this matrix to have passed
    needs:
      - setup
      - tests
    strategy:
      fail-fast: true
      matrix:
        # services to scan over
        data:
          - docker_build_directory: "./service-app"
            image_app_name: "helloworld"
            test_command: "ls -l"
    # we use these a few times, so its easier to generate them once and env
    # vars are visible in the output, so helps with debug
    env:
      local_docker_image: ${{ matrix.data.image_app_name }}:latest
      sarif_file: trivy-results.sarif
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Show environment values
        run: |
          echo "local_docker_image: ${{ env.local_docker_image }}"
          echo "sarif_file: ${{ env.sarif_file }}"
      # build our sample docker image
      - name: Docker build
        # set the working directory to the variable
        working-directory: ${{ matrix.data.docker_build_directory }}
        run: |
          docker build -t ${{ env.local_docker_image }} .
      # to check if things worked, output docker image list
      - name: Docker image list
        run: |
          docker images
      # log in to ECR
      - name: Configure AWS Credentials With Assumed Role to Management
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          # management account role
          role-to-assume: arn:aws:iam::311462405659:role/gh-template-repo-ci
          role-duration-seconds: 900
          role-session-name: OPGExampleWorkflowGithubAction
      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: 311462405659
      - name: Trivy scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        env:
          TRIVY_DB_REPOSITORY: ${{ steps.login_ecr.outputs.registry }}/trivy-db-public-ecr/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: ${{ steps.login_ecr.outputs.registry }}/trivy-db-public-ecr/aquasecurity/trivy-java-db:1
        with:
          image-ref: ${{ env.local_docker_image }}
          severity: "HIGH,CRITICAL"
          format: 'sarif'
          output: ${{ env.sarif_file }}
      - name: Trivy scan upload to github
        uses: github/codeql-action/upload-sarif@5d5cd550d3e189c569da8f16ea8de2d821c9bf7a # v3.31.2
        if: always()
        with:
          sarif_file: ${{ env.sarif_file }}
      # for a lot of our services, there could be a test process here
      - name: Run Tests
        run: |
          ${{ matrix.data.test_command }}
      ######
      ## Push to ECR
      ######
      - name: Push Container
        env:
          SEMVER_TAG: ${{ needs.setup.outputs.semver_tag }}
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          ECR_REPOSITORY: github-template-repository/helloworld
        run: |
          docker tag ${{ env.local_docker_image }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.SEMVER_TAG }}
          docker tag ${{ env.local_docker_image }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY


  # example terraform build stage
  terraform_account_build:
    name: "Terraform Account [Apply: false ]"
    needs:
      - setup
      - build_scan_push
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform.yml@v3.16.0
    with:
      terraform_apply: false
      terraform_version: "${{ needs.setup.outputs.terraform_version }}"
      terraform_directory: "./terraform/account"
      # this would be replaced with the dynamic value
      terraform_workspace: ${{ needs.setup.outputs.terraform_workspace }}
      # normally would need some logic to decide this based on branch name etc
      is_ephemeral: false
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PAGERDUTY_TOKEN: "NONE"
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # final step
  end:
    name: 'End'
    runs-on: 'ubuntu-latest'
    needs:
      - build_scan_push
      - terraform_account_build
    steps:
      - id: end
        name: End
        run: echo "End"
